name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Set node version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install deps
        run: pnpm install --prefer-offline
      - name: Build
        run: pnpm qa
